version: '3.8'
services:
  app:
    container_name: app
    build: ./fastapi
    links:
      - db
    ports:
      - '8080:80'
    volumes:
      - ./fastapi:/app

  db:
    container_name: db
    image: mongo:6.0.5-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

networks:
  default:
